// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prediction_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Serving {

  /// <summary>Holder for reflection information generated from prediction_service.proto</summary>
  public static partial class PredictionServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for prediction_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PredictionServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhwcmVkaWN0aW9uX3NlcnZpY2UucHJvdG8SEnRlbnNvcmZsb3cuc2Vydmlu",
            "ZxoUY2xhc3NpZmljYXRpb24ucHJvdG8aGGdldF9tb2RlbF9tZXRhZGF0YS5w",
            "cm90bxoPaW5mZXJlbmNlLnByb3RvGg1wcmVkaWN0LnByb3RvGhByZWdyZXNz",
            "aW9uLnByb3RvMvwDChFQcmVkaWN0aW9uU2VydmljZRJhCghDbGFzc2lmeRIp",
            "LnRlbnNvcmZsb3cuc2VydmluZy5DbGFzc2lmaWNhdGlvblJlcXVlc3QaKi50",
            "ZW5zb3JmbG93LnNlcnZpbmcuQ2xhc3NpZmljYXRpb25SZXNwb25zZRJYCgdS",
            "ZWdyZXNzEiUudGVuc29yZmxvdy5zZXJ2aW5nLlJlZ3Jlc3Npb25SZXF1ZXN0",
            "GiYudGVuc29yZmxvdy5zZXJ2aW5nLlJlZ3Jlc3Npb25SZXNwb25zZRJSCgdQ",
            "cmVkaWN0EiIudGVuc29yZmxvdy5zZXJ2aW5nLlByZWRpY3RSZXF1ZXN0GiMu",
            "dGVuc29yZmxvdy5zZXJ2aW5nLlByZWRpY3RSZXNwb25zZRJnCg5NdWx0aUlu",
            "ZmVyZW5jZRIpLnRlbnNvcmZsb3cuc2VydmluZy5NdWx0aUluZmVyZW5jZVJl",
            "cXVlc3QaKi50ZW5zb3JmbG93LnNlcnZpbmcuTXVsdGlJbmZlcmVuY2VSZXNw",
            "b25zZRJtChBHZXRNb2RlbE1ldGFkYXRhEisudGVuc29yZmxvdy5zZXJ2aW5n",
            "LkdldE1vZGVsTWV0YWRhdGFSZXF1ZXN0GiwudGVuc29yZmxvdy5zZXJ2aW5n",
            "LkdldE1vZGVsTWV0YWRhdGFSZXNwb25zZUID+AEBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorflow.Serving.ClassificationReflection.Descriptor, global::Tensorflow.Serving.GetModelMetadataReflection.Descriptor, global::Tensorflow.Serving.InferenceReflection.Descriptor, global::Tensorflow.Serving.PredictReflection.Descriptor, global::Tensorflow.Serving.RegressionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
